# Workflow to build and deploy NodeJS React Web Application to a custom Domain
name: Deploy

# Workflow trigger events
on:
  push:
    branches:
      - master

jobs:
  #Job 1
  build:
    name: Build npm environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 17

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  #Job 2
  deploy:
    name: Deploy React web application
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v13
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # cname: cyberanvu.co

      - name: Set custom domain
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKE }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"cname": "cyberanvu.co"}' \
            https://api.github.com/repos/${{ github.repository }}/pages

      - name: show run_id
        run: echo "run_id = ${{ github.run_id }} "
